/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class ObjectJni */

#ifndef _Included_ObjectJni
#define _Included_ObjectJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ObjectJni
 * Method:    ObjectCreate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectJni_ObjectCreate
  (JNIEnv *, jobject);

/*
 * Class:     ObjectJni
 * Method:    InvokeMethod
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectJni_InvokeMethod
  (JNIEnv *, jobject);

/*
 * Class:     ObjectJni
 * Method:    InvokeObjectMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ObjectJni_InvokeObjectMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ObjectJni
 * Method:    ObjectDllMethod
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectJni_ObjectDllMethod
  (JNIEnv *, jobject);

/*
 * Class:     ObjectJni
 * Method:    ObjectDllCallback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectJni_ObjectDllCallback
  (JNIEnv *, jobject);

/*
 * Class:     ObjectJni
 * Method:    ObjectDllFunction
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectJni_ObjectDllFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     ObjectJni
 * Method:    ObjectDllInvokeCallback
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectJni_ObjectDllInvokeCallback
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ObjectJni
 * Method:    ObjectFree
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ObjectJni_ObjectFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
